[package]
name = "zest-app"
description = "The zesterm application: window, chrome, motion, and wiring."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[[bin]]
name = "zesterm"
path = "src/main.rs"

[dependencies]
zest-core.workspace = true
zest-pty.workspace = true
zest-theme.workspace = true
zest-font.workspace = true
zest-render-wgpu.workspace = true
zest-config.workspace = true
zest-input.workspace = true
toml.workspace = true
winit.workspace = true
wgpu.workspace = true
parking_lot.workspace = true
crossbeam-channel.workspace = true
arboard.workspace = true
raw-window-handle.workspace = true
directories.workspace = true
pollster = "0.4"
tracing.workspace = true
tracing-subscriber.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_System_Console",
    "Win32_Storage_FileSystem",
    "Win32_Graphics_Gdi",
    "Win32_UI_WindowsAndMessaging",
] }
