/**
 * Loading `crates/zest-proto/fixtures/` and comparing against it.
 *
 * The fixtures are generated by `cargo xtask fixtures` and gated by
 * `cargo xtask check-fixtures`. Each frame carries the complete framed bytes and,
 * independently, what the **host terminal** held after applying them — read off
 * a real `zest_core::Terminal`, never off the Rust decoder, so this suite is a
 * check against the terminal rather than an agreement between two decoders.
 */

import { readFileSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import { type Color, colorsEqual, colorToString } from '../src/color.ts';
import { type Cell } from '../src/cells.ts';
import { cellFlagNames } from '../src/flags.ts';

const HERE = dirname(fileURLToPath(import.meta.url));
export const FIXTURES_DIR = join(HERE, '../../../../../crates/zest-proto/fixtures');

/** The fixture format this suite understands. Bumped with the exporter. */
const FIXTURE_SCHEMA = 1;

/**
 * The one field the wire does not carry faithfully, and why.
 *
 * `Encoder::encode_row` trims trailing cells by testing `ch`, `bg` and `flags` —
 * not `fg` — so a run of coloured spaces at the end of a row is dropped and
 * rebuilt with the default foreground. Invisible to a renderer, because there is
 * no glyph to colour.
 *
 * The Rust comparator excludes exactly this and names it in its failure message
 * so nobody widens it quietly. Same rule here. **Adding to this list is a change
 * to what the protocol guarantees, not a way to make a test pass.**
 */
export const KNOWN_GAPS = ['fg on a cell that paints nothing'] as const;

export interface StyleSpan {
  0: number;
  1: Color;
  2: Color;
  3: number;
}

export interface MarkExpect {
  col: number;
  marks: string;
}

export interface RowExpect {
  line: number;
  wrapped: boolean;
  text: string;
  styles: Array<[number, Color, Color, number]>;
  marks?: MarkExpect[];
}

export interface FrameExpect {
  cursor: { row: number; col: number; visible: boolean; shape: number };
  modes: number;
  alt_screen: boolean;
  title: string;
  rows: RowExpect[];
}

export interface FixtureFrame {
  kind: 'keyframe' | 'update';
  base?: number;
  seq: number;
  wire: string;
  expect: FrameExpect;
}

export interface Fixture {
  schema: number;
  protocol: number;
  recording: string;
  source: 'vtrec' | 'synthetic';
  cols: number;
  rows: number;
  frames: FixtureFrame[];
}

export function loadFixture(name: string): Fixture {
  const f = JSON.parse(readFileSync(join(FIXTURES_DIR, `${name}.json`), 'utf8')) as Fixture;
  if (f.schema !== FIXTURE_SCHEMA) {
    throw new Error(
      `${name}.json is schema ${f.schema}, this suite reads ${FIXTURE_SCHEMA}` +
        ` -- regenerate with \`cargo xtask fixtures\` or update the loader`,
    );
  }
  if (f.frames.length === 0) throw new Error(`${name}.json has no frames`);
  return f;
}

/** Every recording on disk, so a new one is picked up without editing a list. */
export function fixtureNames(): string[] {
  return readdirSync(FIXTURES_DIR)
    .filter((f) => f.endsWith('.json') && f !== 'bits.json')
    .map((f) => f.replace(/\.json$/, ''))
    .sort();
}

export function loadBits(): {
  schema: number;
  cell_flags: Record<string, number>;
  modes: Record<string, number>;
} {
  return JSON.parse(readFileSync(join(FIXTURES_DIR, 'bits.json'), 'utf8')) as {
    schema: number;
    cell_flags: Record<string, number>;
    modes: Record<string, number>;
  };
}

export function hexToBytes(hex: string): Uint8Array {
  if (hex.length % 2 !== 0) throw new Error(`odd-length hex string (${hex.length})`);
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i++) {
    const byte = Number.parseInt(hex.slice(i * 2, i * 2 + 2), 16);
    if (Number.isNaN(byte)) throw new Error(`bad hex at ${i * 2}`);
    out[i] = byte;
  }
  return out;
}

/** Expand a fixture row's run-length-encoded styles to one entry per cell. */
export function expandExpectedRow(row: RowExpect, cols: number): Cell[] {
  const chars = [...row.text];
  const out: Cell[] = [];

  for (const [n, fg, bg, flags] of row.styles) {
    for (let i = 0; i < n; i++) {
      out.push({ ch: chars[out.length] ?? ' ', fg, bg, flags, marks: '' });
    }
  }
  while (out.length < cols) {
    out.push({ ch: chars[out.length] ?? ' ', fg: 'Default', bg: 'Default', flags: 0, marks: '' });
  }

  for (const m of row.marks ?? []) {
    const cell = out[m.col];
    if (cell !== undefined) out[m.col] = { ...cell, marks: m.marks };
  }
  return out;
}

/**
 * Compare one row cell by cell, applying the single known gap and nothing else.
 *
 * Returns a description of the first difference, or `undefined`. Cell by cell
 * rather than by run: the run boundaries are the encoder's choice and carry no
 * meaning, so two correct implementations can disagree about them.
 */
export function diffRow(got: readonly Cell[], want: readonly Cell[]): string | undefined {
  if (got.length !== want.length) {
    return `row is ${got.length} cells, expected ${want.length}`;
  }

  for (let c = 0; c < got.length; c++) {
    const g = got[c] as Cell;
    const w = want[c] as Cell;

    if (g.ch !== w.ch) {
      return `col ${c}: character ${quote(g.ch)}, expected ${quote(w.ch)}`;
    }
    if (!colorsEqual(g.bg, w.bg)) {
      return `col ${c}: background ${colorToString(g.bg)}, expected ${colorToString(w.bg)}`;
    }
    if (g.flags !== w.flags) {
      return `col ${c}: flags ${cellFlagNames(g.flags)}, expected ${cellFlagNames(w.flags)}`;
    }
    if (g.marks !== w.marks) {
      return `col ${c}: marks ${quote(g.marks)}, expected ${quote(w.marks)}`;
    }

    // KNOWN_GAPS[0]. A cell with no glyph and no background paints nothing, so
    // its foreground is unobservable -- and the encoder drops it.
    const paints = w.ch !== ' ' || !colorsEqual(w.bg, 'Default');
    if (paints && !colorsEqual(g.fg, w.fg)) {
      return `col ${c}: foreground ${colorToString(g.fg)}, expected ${colorToString(w.fg)} on a cell that paints`;
    }
  }
  return undefined;
}

function quote(s: string): string {
  return JSON.stringify(s);
}
