// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a session is asking to be noticed.
 *
 * Mirrors `zest_core::AttentionCause` for [`delta::BlockState`]'s reason:
 * this side carries a `ts_rs` derive, and `zest-core` has to keep building
 * for `wasm32` without one.
 */
export type AttentionCause = "bell" | "notify";
