// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttrId } from "./AttrId";

/**
 * The style an [`AttrId`] stands for.
 */
export type AttrDef = { id: AttrId, 
/**
 * Unresolved, exactly as the grid holds it.
 *
 * `Color::Indexed(1)` stays indexed all the way to the client, so the same
 * session can render under a dark theme on the desktop and a light one on
 * the phone at the same time. Resolving host-side would make the theme a
 * property of the session. → ADR-002.
 */
fg: unknown, bg: unknown, 
/**
 * Bold, italic, underline, inverse and the rest, as raw bits.
 *
 * Pinned to an integer rather than taking `bitflags`' own representation,
 * which is a names-string (`"BOLD | ITALIC"`) in human-readable formats and
 * bits otherwise. A wire type that changes shape with the encoding is a
 * trap for three client implementations, and the names would have to be
 * kept in sync by hand in each of them.
 */
flags: number, };
