// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a connection was refused.
 *
 * A separate message rather than reusing [`HostMessage::Error`][err], because
 * a client must *branch* on this: wait quietly for someone to approve it, stop
 * retrying forever, or back off. Reusing the human-facing error would mean
 * matching on a message string, which is how a client breaks when someone
 * improves the wording.
 *
 * [err]: crate::HostMessage::Error
 */
export type AuthFailure = "signature" | "unknown_client" | "denied" | "timed_out" | "revoked" | "rate_limited" | "version";
