// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * [`zest_core::blocks::BlockContext`], on the wire. Mirrored for the reason
 * `BlockState` is: this side carries the `ts_rs` derive, and `zest-core`
 * has to keep building for `wasm32` without one. Empty strings mean unsaid
 * — the `HostOffer` convention, so a reader shows one row fewer rather
 * than a dash pretending to be a fact.
 */
export type BlockContextPayload = { branch: string, venv: string, kube: string, };
