// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlockContextPayload } from "./BlockContextPayload";
import type { BlockState } from "./BlockState";
import type { ClientId } from "./ClientId";
import type { HostId } from "./HostId";
import type { SessionId } from "./SessionId";

/**
 * One command block, as a search answer carries it.
 *
 * **Not [`crate::BlockPayload`]**, deliberately. That type's three line ids
 * mean something only against the grid that issued them; off it they invite
 * a client to treat a search hit as a keyframe block and look rows up that
 * it does not hold. And a stored block of a session that has ended (ADR-020)
 * has no lines at all, so a shared type would carry a `prompt_line` that is
 * sometimes a fact and sometimes a placeholder — a field nothing can fill
 * reads exactly like one nothing fills (#299).
 *
 * Options here are spelled as plain `null`s on the wire, not skipped keys:
 * this message is a reply and never rides a delta, so the bytes an absent
 * key would save are not worth a second spelling for the TypeScript reader
 * to handle.
 */
export type BlockMatch = { 
/**
 * Whose block. The daemon fills in its own id, exactly as
 * `Registry::list` fills `SessionInfo.addr`; a client merging several
 * hosts' answers keys on it.
 */
host: HostId, 
/**
 * The session that holds the block — `None` for a block whose session
 * is gone and which only a store remembers. A client may re-run the
 * command anywhere, but there is nothing to *activate*: ids restart at
 * one on every daemon start, so a dead session's number names a live
 * stranger.
 */
session: SessionId | null, 
/**
 * `Block::id`, stable for the session's life. With `session`, what
 * `output` in `zest-mcp` takes to fetch the text this deliberately
 * omits.
 */
block: number, 
/**
 * The session's title at answer time, so a row can say *which* zsh when
 * a host has six. Empty when the session is gone or unnamed.
 */
title: string, command: string, 
/**
 * The command was longer than the store keeps and was cut (ADR-020).
 * History to read, not a thing to re-run: a client must not type the
 * first four kilobytes of a pasted script as if they were the whole.
 * Additive; a live block never sets it.
 */
command_truncated: boolean, cwd: string, state: BlockState, 
/**
 * Wall clock at OSC 133;C, milliseconds since the Unix epoch — the
 * host's stamp, so "2m ago" on another machine means something against
 * a shared epoch.
 */
started_ms: number | null, 
/**
 * Wall clock at OSC 133;D, same epoch. `None` while it runs.
 */
ended_ms: number | null, 
/**
 * Branch, venv, cluster as of the command's start — the same payload
 * the keyframe carries, so `zest-mcp`'s `context` key reads identically
 * from `blocks` and from `search_blocks`.
 */
context: BlockContextPayload | null, 
/**
 * The client the daemon saw type it. Provenance, never authorization —
 * see [`crate::BlockPayload::author`].
 */
author: ClientId | null, };
