// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlockState } from "./BlockState";

/**
 * One command and its output, as the host has it.
 *
 * Line ids are `i64` to match [`RowPayload::line`] — a client compares the two
 * to decide which rows a block covers, and two integer types that must agree
 * is a conversion bug waiting for a session long enough to matter.
 */
export type BlockPayload = { 
/**
 * Stable for the life of the session; the key an upsert replaces on.
 */
id: number, 
/**
 * First line of the prompt (OSC 133;A).
 *
 * The integer is pinned to `number` for [`RowPayload::line`]'s reason,
 * on all three line fields — they are compared against it, and two
 * integer types that must agree is a conversion bug waiting to happen.
 * (`output_line`/`end_line` are `number | null`: same integer, plus the
 * `null` their `Option` really does put on the wire.)
 */
prompt_line: number, 
/**
 * First line of command output (OSC 133;C), once it starts.
 */
output_line: number | null, 
/**
 * Last line, once the command has finished (OSC 133;D).
 *
 * `None` while it runs, and a client must render such a block to the
 * bottom rather than waiting — that is what makes a long build readable
 * while it happens instead of only afterwards.
 */
end_line: number | null, state: BlockState, command: string, cwd: string, 
/**
 * Wall clock at OSC 133;C, milliseconds since the Unix epoch. Additive
 * (`serde(default)`), so an old host simply sends blocks without times.
 *
 * A *start* stamp, never a live elapsed: `diff_blocks` resends a block
 * whenever any field changes, and an elapsed field would resend every
 * running block on every tick. `f64` on the TypeScript side would also be
 * tempting and wrong — see the `rmp-serde` integer-width trap; epoch
 * millis stay under 2^53 for the next 285,000 years, so `number` holds.
 * (`ts(type = "number")`, not `"number | null"`: `skip_serializing_if =
 * "Option::is_none"` means `None` travels as an absent key, never as
 * `null` — the binding was overstating the wire, #15's class of bug.)
 */
started_ms?: number, 
/**
 * Wall clock at OSC 133;D, same epoch.
 */
ended_ms?: number, };
