// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a command ended.
 *
 * Mirrors `zest_core::BlockState` rather than reusing it, for the same reason
 * [`RowPayload`] mirrors a `Row`: the wire type carries a `ts_rs` derive, and
 * `zest-core` has to keep building for `wasm32` with no such dependency.
 */
export type BlockState = { "state": "prompt" } | { "state": "running" } | { "state": "finished", exit_code: number | null, };
