// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Combining marks for one cell of a [`Run`].
 */
export type CellMarks = { 
/**
 * Offset of the cell within its run, in cells.
 */
at: number, 
/**
 * The marks themselves, in the order they were applied.
 */
marks: string, };
