// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientId } from "./ClientId";
import type { Nonce32 } from "./Nonce32";
import type { Pub32 } from "./Pub32";
import type { Seq } from "./Seq";
import type { SessionAddr } from "./SessionAddr";
import type { Sig64 } from "./Sig64";

/**
 * What a client sends.
 */
export type ClientMessage = { "t": "hello", version: number, client: ClientId, 
/**
 * Human-readable, for the host's audit log and approval prompt.
 *
 * Covered by both signatures. An unsigned label would let anyone on
 * the path make the host's approval prompt read "pair with
 * andy-phone?" for a connection that is not the phone — and the prompt
 * text is the human's entire decision input.
 */
label: string, 
/**
 * The client's half of the handshake freshness.
 *
 * `#[serde(default)]` is deliberate and is not laxity. Without it a
 * version-1 `Hello` fails to *decode*, and the peer is told "message
 * was not understood" instead of the truthful "protocol 1 is not
 * compatible with 2". The default is all zeroes, which
 * [`Nonce32::is_absent`] recognises and the host refuses explicitly —
 * so the version check runs first and says the useful thing.
 */
nonce: Nonce32, 
/**
 * The client's ephemeral X25519 public key.
 *
 * Signed into the transcript alongside the nonces, so the *existing*
 * Ed25519 signatures certify it — that is what removes the need for a
 * certificate type or a stored static key. `#[serde(default)]` for the
 * same reason `nonce` has it: a version-2 `Hello` must fail the
 * version check with a truthful message rather than fail to decode
 * and be told "message was not understood".
 */
dh: Pub32, 
/**
 * Ask to be told when this host's session list changes.
 *
 * A live tab picker needs to hear about sessions other clients
 * create, close, or attach to; without asking, `Sessions` only ever
 * answers this connection's own requests and a listing goes stale
 * the moment someone else acts. A field rather than a new message:
 * both enums are tagged, an unknown tag fails the *whole* message on
 * an older peer, and a field an old daemon ignores degrades to
 * exactly today's behavior — the client notices no pushes arrive and
 * falls back to polling.
 */
watch_sessions: boolean, 
/**
 * Ask to be told when a device is waiting to be approved.
 *
 * The desktop approval modal's subscription: [`HostMessage::PairingRequested`]
 * pushes follow, request and tombstone alike. **Honoured on loopback
 * only** — the same authority rule as `PairingDecision`, decided by
 * the transport, so a LAN connection that sets it is silently never
 * subscribed rather than refused. A field rather than a new message
 * for `watch_sessions`' reason exactly: `#[serde(default)]` degrades
 * to today's behavior on an older daemon, which simply never pushes.
 */
watch_pairings: boolean, 
/**
 * Ask what this machine can offer, and to be told when that changes.
 *
 * The launcher's subscription (#262). A client that sets it gets a
 * [`HostOffer`] on the first `Sessions` reply and another whenever the
 * far config reloads — which is how the `+` menu can show a machine's
 * own profiles at all, and how a fleet card fills its `os` row with a
 * fact rather than a dash.
 *
 * A field rather than a new message, for `watch_sessions`' reason
 * exactly, and here the reason is sharper than it is there: a new
 * `HostMessage` tag does not merely go unread on an older peer, it
 * **kills the connection**, because `DaemonClient::recv` maps a frame
 * it cannot decode to `DaemonError::Transport`. An old daemon ignores
 * this flag and sends no offer; a new daemon sends none to a client
 * that did not ask. Both degrade to exactly today's behaviour.
 */
watch_hosts: boolean, 
/**
 * Ask to be told when an attached session asks to be noticed.
 *
 * The gate on [`HostMessage::Attention`], and it is load-bearing
 * rather than tidy: a `HostMessage` tag an older client cannot decode
 * does not go unread, it **kills the connection** — `DaemonClient::recv`
 * maps a frame it cannot decode to `DaemonError::Transport`. So the
 * daemon must never send one to a client that did not ask, and this
 * is how it knows. `#[serde(default)]` for `watch_sessions`' reason:
 * an old daemon ignores the flag and sends nothing, which is exactly
 * today's behaviour at both ends.
 */
watch_signals: boolean, } | { "t": "auth", signature: Sig64, } | { "t": "pairing_decision", client: ClientId, approve: boolean, } | { "t": "enroll", code: string, } | { "t": "list_dir", path: string, } | { "t": "request_keyframe", session: SessionAddr, } | { "t": "list_sessions" } | { "t": "create_session", 
/**
 * Empty means the host's default shell.
 */
command: string, cwd: string, cols: number, rows: number, 
/**
 * Extra environment for the child, layered over the host's own.
 *
 * Ordered and last-wins, and **an empty value unsets** — the same
 * convention `CommandSpec.env` and the `shell.env` setting already
 * carry, kept identical here so a launch can be handed straight to
 * the pty rather than translated on the way.
 *
 * No new privilege: `command` is already arbitrary execution on the
 * host, which is the argument `ReadFile` below makes about itself.
 * What this *is* is the seam a per-profile environment needs — without
 * it `shell.env` is a setting that does nothing, because the only
 * path that applied it was the in-process `--no-daemon` fallback
 * (#488).
 *
 * Skipped when empty so an ordinary launch is byte-identical to what
 * a daemon predating the field sent, and the conformance fixtures do
 * not move.
 */
env: Array<[string, string]>, } | { "t": "attach", session: SessionAddr, cols: number, rows: number, observe: boolean, } | { "t": "detach", session: SessionAddr, } | { "t": "input", session: SessionAddr, bytes: Array<number>, } | { "t": "resize", session: SessionAddr, cols: number, rows: number, } | { "t": "ack", session: SessionAddr, seq: Seq, } | { "t": "request_scrollback", session: SessionAddr, from_line: number, count: number, } | { "t": "close_session", session: SessionAddr, } | { "t": "read_file", 
/**
 * The file, as the host reads paths. Absolute, or resolved against
 * `cwd`; opaque to the client, like `CreateSession.cwd`.
 */
path: string, 
/**
 * The base a relative `path` resolves against. Empty means `path`
 * must already be absolute.
 */
cwd: string, } | { "t": "write_file", path: string, cwd: string, 
/**
 * The whole new content. Bounded by `MAX_FRAME` at the encoder.
 */
data: Array<number>, 
/**
 * [`HostMessage::FileContents::hash`] from the read this edit was
 * based on, so a file that moved underneath is refused instead of
 * clobbered. Empty means "create it, and refuse if it exists".
 *
 * Every way the disk can disagree — it changed, it is gone, it
 * appeared where the client expected nothing — comes back as one
 * `conflict`, so the client has one branch to write rather than four
 * that each have to be told apart from an I/O failure.
 */
base_hash: string, } | { "t": "git_diff", cwd: string, };
