// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A device that attaches to hosts. Same construction, different role.
 *
 * Separate from [`HostId`] on purpose even though the bytes look identical: a
 * machine can be both — the Windows box hosts its own shells *and* attaches to
 * the Mac — and conflating the two roles is how an authorization check ends up
 * asking the wrong question.
 */
export type ClientId = string;
