// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientId } from "./ClientId";
import type { Nonce32 } from "./Nonce32";
import type { Seq } from "./Seq";
import type { SessionAddr } from "./SessionAddr";
import type { Sig64 } from "./Sig64";

/**
 * What a client sends.
 */
export type ClientMessage = { "t": "hello", version: number, client: ClientId, 
/**
 * Human-readable, for the host's audit log and approval prompt.
 *
 * Covered by both signatures. An unsigned label would let anyone on
 * the path make the host's approval prompt read "pair with
 * andy-phone?" for a connection that is not the phone — and the prompt
 * text is the human's entire decision input.
 */
label: string, 
/**
 * The client's half of the handshake freshness.
 *
 * `#[serde(default)]` is deliberate and is not laxity. Without it a
 * version-1 `Hello` fails to *decode*, and the peer is told "message
 * was not understood" instead of the truthful "protocol 1 is not
 * compatible with 2". The default is all zeroes, which
 * [`Nonce32::is_absent`] recognises and the host refuses explicitly —
 * so the version check runs first and says the useful thing.
 */
nonce: Nonce32, 
/**
 * Ask to be told when this host's session list changes.
 *
 * A live tab picker needs to hear about sessions other clients
 * create, close, or attach to; without asking, `Sessions` only ever
 * answers this connection's own requests and a listing goes stale
 * the moment someone else acts. A field rather than a new message:
 * both enums are tagged, an unknown tag fails the *whole* message on
 * an older peer, and a field an old daemon ignores degrades to
 * exactly today's behavior — the client notices no pushes arrive and
 * falls back to polling.
 */
watch_sessions: boolean, } | { "t": "auth", signature: Sig64, } | { "t": "pairing_decision", client: ClientId, approve: boolean, } | { "t": "request_keyframe", session: SessionAddr, } | { "t": "list_sessions" } | { "t": "create_session", 
/**
 * Empty means the host's default shell.
 */
command: string, cwd: string, cols: number, rows: number, } | { "t": "attach", session: SessionAddr, cols: number, rows: number, } | { "t": "detach", session: SessionAddr, } | { "t": "input", session: SessionAddr, bytes: Array<number>, } | { "t": "resize", session: SessionAddr, cols: number, rows: number, } | { "t": "ack", session: SessionAddr, seq: Seq, } | { "t": "request_scrollback", session: SessionAddr, from_line: bigint, count: number, } | { "t": "close_session", session: SessionAddr, };
