// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A cell's foreground or background color, unresolved.
 *
 * Fits in 4 bytes so that [`crate::Cell`] can stay at 16.
 */
export type Color = "Default" | { "Indexed": number } | { "Rgb": [number, number, number] };
