// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a [`ClientMessage::SetConfig`] does.
 *
 * A typed enum rather than a string because these are the operations that
 * exist and a client naming one that does not is a bug in the client, not a
 * value to display. Contrast [`HostMessage::ConfigWritten::invalidation`],
 * which is a string precisely because a new class must not be a coordinated
 * wire change.
 */
export type ConfigOp = "set" | "reset" | "create-profile" | "copy-profile" | "rename-profile" | "remove-profile";
