// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One theme a machine has.
 */
export type ConfigTheme = { id: string, name: string, 
/**
 * `dark` or `light`.
 */
mode: string, 
/**
 * Shipped with zesterm rather than imported by this machine's user. What
 * separates "everyone has this" from "this one is on that laptop".
 */
builtin: boolean, };
