// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One settings value, as this machine resolves it.
 */
export type ConfigValue = { 
/**
 * Dotted, e.g. `typography.size_pt`.
 */
key: string, 
/**
 * The value in its **TOML spelling** — `20.0`, `true`, `"nord"`,
 * `["Berkeley Mono", "monospace"]`.
 *
 * Not JSON, and not a typed sum, for three reasons that all point the
 * same way. The file is TOML, so an agent reading `size_pt = 20.0` in
 * `config.toml` and reading this see the same text, and the two pictures
 * compose. The write direction takes the same spelling straight to
 * `toml_edit`, so `14` stays `14` rather than becoming `14.0` in
 * somebody's hand-written file — the exact problem `UiField.integer`
 * exists for. And it costs `zest-proto` no dependency, in a crate whose
 * manifest says it is "data and the rules for encoding it, nothing else".
 *
 * The same trade [`HostMessage::GitDiffResult::diff`] makes: parsing is a
 * small pure function in each client, where a wire-level value vocabulary
 * would be a large surface frozen on the day it ships.
 */
value: string, 
/**
 * Which layer wrote it: `default`, `user`, `profile:<name>`,
 * `workspace`, `command-line`.
 *
 * The machine-readable spelling, deliberately **not** `Source`'s
 * `Display` — that one is prose ("set by profile `k8s-prod`"), and a
 * client parsing prose is the thing this field exists to avoid.
 */
source: string, };
