// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfigVariant } from "./ConfigVariant";

/**
 * What one settings key accepts — the wire half of `zest_config::ui::UiField`.
 *
 * Restated here rather than imported, exactly as [`HostProfile`] restates
 * `ProfileMeta` and for the same reason (ADR-014): `zest-proto` importing
 * `zest-config` would put a settings cascade inside the frozen wire crate.
 * The projection lives in the daemon.
 */
export type ConfigField = { key: string, 
/**
 * The display group the settings UIs put it in.
 */
group: string, 
/**
 * `toggle`, `number`, `slider`, `select`, `theme-picker`, … — the
 * kebab-case spelling of `zest_config::ui::Widget`.
 */
widget: string, 
/**
 * The field's doc comment, which is what a person or a model reads to
 * decide what to set it to.
 */
description: string, 
/**
 * Schema minimum and maximum, when the schema gives both.
 */
range?: [number, number], 
/**
 * The schema types this as an integer, so a write must spell it `14`
 * rather than `14.0`.
 */
integer: boolean, 
/**
 * The legal values, when there is a closed set of them. Empty for a
 * picker whose roster is live state rather than schema — a theme list is
 * [`ConfigState::themes`], not this.
 */
variants: Array<ConfigVariant>, 
/**
 * The schema default, in the same TOML spelling as
 * [`ConfigValue::value`], so "is this still the default" is a string
 * comparison rather than a second encoding to agree about.
 */
default: string, 
/**
 * The schema's advisory restart flag. `invalidate::class_of` is the
 * authoritative answer and is what [`HostMessage::ConfigWritten`]
 * reports; this covers fewer keys and exists for a client holding only
 * the schema.
 */
restart_hint: boolean, };
