// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One option of a [`ConfigField`] with a closed set of values.
 */
export type ConfigVariant = { 
/**
 * The wire value, exactly as it must be spelled in the file.
 */
value: string, 
/**
 * The variant's doc comment; empty when it has none.
 */
description: string, };
