// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfigValue } from "./ConfigValue";

/**
 * One profile as its file describes it.
 *
 * **Carries `host` and `ask_host`, which [`HostProfile`] deliberately does
 * not**, and the difference is the whole reason these are two types rather
 * than one. `HostProfile` is a *launch target*: a client resolves it and then
 * dials, so a `host` key there invites resolution against the **viewer's**
 * fleet, which is the one way that feature could start a command on the wrong
 * computer (ADR-014). This is a *view of a file*, for a client about to edit
 * that file, and nothing launches from it.
 *
 * Nothing structural enforces that. A launcher wired to this type later would
 * reintroduce exactly the bug ADR-014 removed, so the rule lives here, in the
 * tool descriptions that expose it, and nowhere else it can be missed.
 */
export type ConfigProfile = { name: string, command: string, 
/**
 * The machine this profile is pinned to, as the *file* spells it. Empty
 * means the machine that answered.
 */
host: string, ask_host: boolean, starting_directory: string, 
/**
 * `from-shell`, `profile-name`, or the literal custom title.
 */
tab_title: string, color_scheme: string, tab_color?: number, icon: string, color_from: string, 
/**
 * The settings keys this profile overrides, each with `source` reading
 * `profile:<name>` or `profile:defaults` — so "this profile sets it" and
 * "it fell through to Defaults" are distinguishable, which is the
 * question anyone editing a profile is actually asking.
 */
overrides: Array<ConfigValue>, 
/**
 * Keys in the profile's table that are neither profile-only nor schema
 * keys — the typo surface.
 */
unknown_keys: Array<string>, };
