// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who produced a [`ContextFact`], carried per fact rather than documented,
 * because the distinction has to survive into every payload an agent reads —
 * a tool description is not where a trust boundary lives (ADR-015).
 */
export type ContextSource = "daemon_probe" | "shell_report";
