// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContextSource } from "./ContextSource";

/**
 * One labeled thing true about the session's surroundings.
 */
export type ContextFact = { 
/**
 * `venv`, `conda`, `kube`, `node`, `python`, `rust`, `ssh_host`, …
 */
key: string, value: string, 
/**
 * Who said so — and therefore how far it can be trusted.
 */
source: ContextSource, };
