// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttrDef } from "./AttrDef";
import type { BlockPayload } from "./BlockPayload";
import type { DeltaOp } from "./DeltaOp";

/**
 * A batch applied atomically.
 */
export type Delta = { 
/**
 * Attributes first used in this batch. Cumulative for the session.
 */
attrs: Array<AttrDef>, ops: Array<DeltaOp>, 
/**
 * Blocks that changed in this batch, to be inserted or replaced by `id`.
 *
 * # Why a field and not a `DeltaOp`
 *
 * `DeltaOp` is `#[serde(tag = "op")]`, so a new variant is **not**
 * additive: a peer that predates it fails to decode the whole [`Delta`],
 * not just the op it does not know. A field with `serde(default)` is what
 * `Run::marks` and `Keyframe::modes` already are, and it decodes
 * everywhere.
 *
 * It is also the honest shape. The ops are an ordered sequence with two
 * asserted orderings ([`Delta::scrolls_come_first`],
 * [`Delta::screen_switch_comes_first`]); block upserts are keyed and
 * order-independent. They are applied *after* the ops because they name
 * absolute line ids that the rows in the same batch establish.
 */
blocks: Array<BlockPayload>, };
