// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttrId } from "./AttrId";
import type { CursorState } from "./CursorState";
import type { RowPayload } from "./RowPayload";

/**
 * One change to the grid.
 */
export type DeltaOp = { "op": "scroll", top: number, bottom: number, lines: number, } | { "op": "row", row: number, payload: RowPayload, } | { "op": "erase", top: number, left: number, bottom: number, right: number, attr: AttrId, } | { "op": "cursor", cursor: CursorState, } | { "op": "sb_push", payload: RowPayload, } | { "op": "alt_screen", active: boolean, } | { "op": "title", title: string, } | { "op": "modes", bits: number, };
