// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttrDef } from "./AttrDef";
import type { DeltaOp } from "./DeltaOp";

/**
 * A batch applied atomically.
 */
export type Delta = { 
/**
 * Attributes first used in this batch. Cumulative for the session.
 */
attrs: Array<AttrDef>, ops: Array<DeltaOp>, };
