// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Git, structured, because three clients render its parts differently.
 */
export type GitContext = { 
/**
 * The branch name, or the short hash when detached.
 */
branch: string, detached: boolean, 
/**
 * Whether the tree has uncommitted changes.
 *
 * `None` until something actually asks git — answering honestly means a
 * subprocess, and the probe that ships first runs none. An `Option`
 * because "clean" and "unknown" rendering the same chip is exactly the
 * dash-pretending-to-be-a-fact the `HostOffer` fields warn about.
 */
dirty?: boolean, };
