// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HostProfile } from "./HostProfile";

/**
 * What a machine can offer a client: what it *is*, and what it can launch.
 *
 * Answers two questions the protocol could not ask before (#262): the fleet
 * card's `os` row, and the `+` launcher's "what can I run on that machine".
 * Both were structurally unanswerable — `Welcome { host, label }` was the
 * entire description of a machine a client ever received.
 *
 * Facts, deliberately, and not a capability matrix. Nothing here is matched
 * on to decide whether a feature is available; it is rendered, and a client
 * that meets an empty string shows one row fewer.
 */
export type HostOffer = { 
/**
 * `std::env::consts::OS` — `windows`, `macos`, `linux`.
 *
 * `#[serde(default)]` like every other field here, and the reason is the
 * same one that made this a field rather than a new message: a required
 * field a future peer omits does not fail *softly*. Decoding the whole
 * `Sessions` message fails, and `DaemonClient::recv` maps that to a
 * transport error, which ends the connection — so one absent string would
 * cost a client its session list too.
 */
os: string, 
/**
 * `std::env::consts::ARCH` — `x86_64`, `aarch64`.
 */
arch: string, 
/**
 * The OS as the machine names itself — `Darwin 24.5.0`,
 * `Linux 6.8.0-31-generic` — best effort.
 *
 * Carries the kernel's *name* as well as its release, because this is the
 * only place that name reaches a client: [`Self::os`] is
 * `std::env::consts::OS`, which says `macos` where design §7's card says
 * `Darwin`.
 *
 * Empty when unknown, never a placeholder: those cards show only what is
 * actually known, and a dash pretending to be a fact is the thing that
 * rule exists to prevent.
 */
os_version: string, 
/**
 * What a session with an empty `CreateSession.command` will run.
 *
 * So a launcher row for a remote profile with no command of its own can
 * say what it will start, instead of showing this machine's shell for a
 * session that will run the far one's.
 */
default_shell: string, 
/**
 * This machine's own launch targets, resolved through its own Defaults.
 */
profiles: Array<HostProfile>, };
