// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One launch target a machine publishes.
 *
 * The launcher-facing half of `zest_config::profiles::ProfileMeta`, and
 * notably **not** its `host` or `ask_host` fields: a profile published by a
 * machine is pinned to that machine by construction, and re-sending a `host`
 * key invites a client to resolve a label against its own fleet and send the
 * launch somewhere else entirely.
 *
 * Values arrive already folded through that host's `profiles.defaults`, so a
 * client renders and launches what it was told rather than re-running a
 * cascade over a config it does not have.
 */
export type HostProfile = { name: string, 
/**
 * Empty means this host's default shell — the same convention
 * `CreateSession.command` uses, so a launch can pass it straight through.
 */
command: string, starting_directory: string, icon: string, color_scheme: string, tab_color: number | null, };
