// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttrDef } from "./AttrDef";
import type { AuthFailure } from "./AuthFailure";
import type { BlockPayload } from "./BlockPayload";
import type { ClientId } from "./ClientId";
import type { CursorState } from "./CursorState";
import type { Delta } from "./Delta";
import type { HostId } from "./HostId";
import type { Nonce32 } from "./Nonce32";
import type { RowPayload } from "./RowPayload";
import type { Seq } from "./Seq";
import type { SessionAddr } from "./SessionAddr";
import type { SessionInfo } from "./SessionInfo";
import type { Sig64 } from "./Sig64";

/**
 * What a host sends.
 */
export type HostMessage = { "t": "welcome", version: number, host: HostId, label: string, } | { "t": "challenge", version: number, host: HostId, label: string, nonce: Nonce32, signature: Sig64, } | { "t": "auth_pending", code: string, expires_in_secs: number, } | { "t": "auth_failed", reason: AuthFailure, message: string, } | { "t": "pairing_requested", client: ClientId, label: string, code: string, remote: string, } | { "t": "sessions", sessions: Array<SessionInfo>, } | { "t": "keyframe", session: SessionAddr, seq: Seq, cols: number, rows: number, rows_data: Array<RowPayload>, attrs: Array<AttrDef>, cursor: CursorState, 
/**
 * `zest_core::Modes::bits()`. See [`DeltaOp::Modes`].
 *
 * A keyframe is a complete state, and a client encodes its own
 * keystrokes — without this, a freshly attached session has broken
 * arrow keys until the host next happens to change a mode.
 */
modes: number, 
/**
 * Every command block the host holds.
 *
 * Additive, so a peer that predates it still decodes — it simply has
 * no semantic view of the session, which is what every peer had
 * before this existed.
 */
blocks: Array<BlockPayload>, } | { "t": "update", session: SessionAddr, base: Seq, seq: Seq, delta: Delta, } | { "t": "scrollback", session: SessionAddr, from_line: bigint, rows_data: Array<RowPayload>, 
/**
 * Every attribute these rows name.
 *
 * Additive, so a peer that predates it still decodes — but a peer that
 * ignores it renders history in whatever style it last held, because
 * scrollback is prepended rather than diffed and no later delta will
 * define these ids.
 */
attrs: Array<AttrDef>, } | { "t": "exited", session: SessionAddr, code: number | null, } | { "t": "error", session: SessionAddr | null, message: string, };
