// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttentionCause } from "./AttentionCause";
import type { AttrDef } from "./AttrDef";
import type { AuthFailure } from "./AuthFailure";
import type { BlockPayload } from "./BlockPayload";
import type { ClientId } from "./ClientId";
import type { CursorState } from "./CursorState";
import type { Delta } from "./Delta";
import type { HostId } from "./HostId";
import type { HostOffer } from "./HostOffer";
import type { Nonce32 } from "./Nonce32";
import type { Progress } from "./Progress";
import type { Pub32 } from "./Pub32";
import type { RowPayload } from "./RowPayload";
import type { Seq } from "./Seq";
import type { SessionAddr } from "./SessionAddr";
import type { SessionId } from "./SessionId";
import type { SessionInfo } from "./SessionInfo";
import type { Sig64 } from "./Sig64";

/**
 * What a host sends.
 */
export type HostMessage = { "t": "welcome", version: number, host: HostId, label: string, } | { "t": "challenge", version: number, host: HostId, label: string, nonce: Nonce32, 
/**
 * The host's ephemeral X25519 public key. See `Hello::dh`.
 *
 * **This message is the switch.** Everything after a Challenge is
 * sealed, in both directions; everything up to and including it is
 * plaintext. Positional rather than per-message-type, because a table
 * of which variants are encrypted is a table two independent
 * implementations can disagree about — and the set of refusals that
 * happen *before* a Challenge is exactly "the host never sent one".
 */
dh: Pub32, signature: Sig64, } | { "t": "auth_pending", code: string, expires_in_secs: number, } | { "t": "auth_failed", reason: AuthFailure, message: string, } | { "t": "pairing_requested", client: ClientId, label: string, code: string, remote: string, 
/**
 * How long the code is still worth comparing, mirroring
 * [`HostMessage::AuthPending`]. `0` from a daemon that predates the
 * field — treat as unknown, not as already-expired.
 */
expires_in_secs: number, resolved: boolean, } | { "t": "sessions", sessions: Array<SessionInfo>, 
/**
 * The session this reply's `CreateSession` produced, when it did.
 *
 * Before this existed the client picked `sessions.last()`, which is
 * wrong the moment two clients create on one host concurrently —
 * each may adopt the other's shell. Absent on listings and pushes.
 */
created: SessionId | null, 
/**
 * What this machine can offer: its facts, and its own profiles.
 *
 * Sent only to connections that asked (`Hello.watch_hosts`), and only
 * when there is something new to say — `Some` on the first reply and
 * again whenever the host's config reloads, `None` on every ordinary
 * session push. `None` is therefore "nothing new", which is also
 * exactly what a daemon predating this field sends, so one reading
 * serves both.
 *
 * **On `Sessions` rather than a message of its own**, and that is the
 * honest cost of the no-new-tag rule rather than a natural fit — see
 * docs/CONTRACTS.md. It is less arbitrary than it first looks:
 * `Sessions` is already "what this host has to offer you", already
 * both the `ListSessions` reply and the watch push, and already what a
 * client re-reads on every reconnect.
 */
offer: HostOffer | null, } | { "t": "enroll_result", ok: boolean, account: string | null, message: string, } | { "t": "keyframe", session: SessionAddr, seq: Seq, cols: number, rows: number, rows_data: Array<RowPayload>, attrs: Array<AttrDef>, cursor: CursorState, 
/**
 * `zest_core::Modes::bits()`. See [`DeltaOp::Modes`].
 *
 * A keyframe is a complete state, and a client encodes its own
 * keystrokes — without this, a freshly attached session has broken
 * arrow keys until the host next happens to change a mode.
 */
modes: number, 
/**
 * Every command block the host holds.
 *
 * Additive, so a peer that predates it still decodes — it simply has
 * no semantic view of the session, which is what every peer had
 * before this existed.
 */
blocks: Array<BlockPayload>, 
/**
 * The id from which `blocks` is authoritative; see
 * [`Keyframe::blocks_from`](crate::Keyframe::blocks_from).
 *
 * Additive, so an older peer still decodes. Its default of 0 makes a
 * keyframe from a host that predates this replace the client's list
 * wholesale, which is what the browser's `GridView` already did.
 */
blocks_from: number, 
/**
 * The session's title at this instant.
 *
 * A keyframe is a complete state, and the title was the one piece of
 * it that only travelled as a *change* (`DeltaOp::Title`) — so a tab
 * attaching to a session already titled `vim` showed blank until the
 * host next happened to retitle. Empty means untitled and travels as
 * absent.
 */
title: string, 
/**
 * How many times ED 3 has destroyed the host's scrollback; see
 * [`Keyframe::history_clears`](crate::Keyframe::history_clears).
 *
 * Additive (`blocks_from`'s precedent), so an older peer still
 * decodes; its default of 0 never advances a replica's shadow, so a
 * host that predates this simply never announces a clear — which is
 * what every host did before it existed.
 */
history_clears: number, } | { "t": "update", session: SessionAddr, base: Seq, seq: Seq, delta: Delta, } | { "t": "scrollback", session: SessionAddr, 
/**
 * A line id — `ts(type = "number")` for
 * [`RowPayload::line`](crate::delta::RowPayload)'s reason.
 */
from_line: number, rows_data: Array<RowPayload>, 
/**
 * Every attribute these rows name.
 *
 * Additive, so a peer that predates it still decodes — but a peer that
 * ignores it renders history in whatever style it last held, because
 * scrollback is prepended rather than diffed and no later delta will
 * define these ids.
 */
attrs: Array<AttrDef>, } | { "t": "exited", session: SessionAddr, code: number | null, } | { "t": "attention", session: SessionAddr, cause: AttentionCause, } | { "t": "progress", session: SessionAddr, progress: Progress, } | { "t": "error", session: SessionAddr | null, message: string, };
