// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A machine in the mesh. The fingerprint of its long-lived public key.
 */
export type HostId = string;
