// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Fresh random bytes contributed to one handshake.
 *
 * `Default` is all zeroes, which exists only so a peer speaking the previous
 * protocol still *decodes* — see [`ClientMessage::Hello`](crate::ClientMessage)
 * — and is rejected explicitly rather than treated as a nonce.
 */
export type Nonce32 = string;
