// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The flavour of a determinate [`Progress`].
 */
export type ProgressState = "normal" | "error" | "warning";
