// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProgressState } from "./ProgressState";

/**
 * How a long job is going, as `OSC 9;4` reports it.
 *
 * Mirrors `zest_core::Progress` for [`BlockState`]'s reason: this side
 * carries a `ts_rs` derive, and `zest-core` has to keep building for `wasm32`
 * without one.
 */
export type Progress = { "kind": "none" } | { "kind": "at", percent: number, state: ProgressState, } | { "kind": "indeterminate" };
