// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An X25519 public key, ephemeral to one connection.
 *
 * Beside `Nonce32` rather than reusing it, though both are 32 bytes: a nonce
 * is freshness and this is key material, and a type that means either is a
 * type a caller can pass to the wrong parameter. The wire carries the bytes;
 * `zest-mesh` decides what they mean — this crate has no crypto dependency
 * and gains none here.
 * `Default` is all zeroes, and exists for exactly one reason: so a peer
 * speaking the previous protocol reaches the *version* check with a decodable
 * message instead of failing to parse. It is never a usable key —
 * `is_absent` recognises it and `zest-mesh` refuses to derive from it.
 */
export type Pub32 = string;
