// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Run } from "./Run";

/**
 * One row, as runs.
 */
export type RowPayload = { 
/**
 * Absolute line id — stable across scrolling and scrollback eviction.
 *
 * Absolute rather than viewport-relative so a selection, a command block,
 * and a scrollback request all name the same thing on every client even as
 * output pushes the viewport along.
 *
 * `number`, not the `bigint` ts-rs would derive: `rmp-serde` writes the
 * narrowest integer that fits, so every realistic id reaches JavaScript
 * as a plain `number` — and the one id outside ±2^53 a host actually
 * sends, the `i64::MIN` a blank row is padded with, is a power of two
 * and therefore exact as a double (#14).
 */
line: number, runs: Array<Run>, 
/**
 * The line continues onto the next one rather than ending.
 *
 * Carried so a client can copy a wrapped line without a spurious newline,
 * and so reflow becomes possible later without a wire change.
 */
wrapped: boolean, };
