// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Run } from "./Run";

/**
 * One row, as runs.
 */
export type RowPayload = { 
/**
 * Absolute line id — stable across scrolling and scrollback eviction.
 *
 * Absolute rather than viewport-relative so a selection, a command block,
 * and a scrollback request all name the same thing on every client even as
 * output pushes the viewport along.
 */
line: bigint, runs: Array<Run>, 
/**
 * The line continues onto the next one rather than ending.
 *
 * Carried so a client can copy a wrapped line without a spurious newline,
 * and so reflow becomes possible later without a wire change.
 */
wrapped: boolean, };
