// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttrId } from "./AttrId";
import type { CellMarks } from "./CellMarks";

/**
 * A stretch of cells sharing one attribute.
 */
export type Run = { attr: AttrId, 
/**
 * How many grid cells this run occupies.
 *
 * Not derivable from `text`: a CJK character is one `char` and two cells, a
 * ZWJ family emoji is seven codepoints and two cells. The host knows;
 * clients must not recompute. See the module docs.
 */
cells: number, text: string, 
/**
 * Combining marks, for the cells in this run that have any.
 *
 * A separate field rather than more characters in `text`, and that is the
 * whole point: `text` stays exactly one `char` per cell, so a client never
 * has to know which codepoints combine. Appending marks inline would make
 * every decoder carry a Unicode table and get the grouping right, which is
 * the same class of mistake `Run::cells` exists to prevent for widths.
 *
 * Additive, so a peer that predates it decodes fine and simply renders
 * `e` where `é` was intended — which is what every peer did before this
 * existed.
 */
marks: Array<CellMarks>, };
