// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttrId } from "./AttrId";

/**
 * A stretch of cells sharing one attribute.
 */
export type Run = { attr: AttrId, 
/**
 * How many grid cells this run occupies.
 *
 * Not derivable from `text`: a CJK character is one `char` and two cells, a
 * ZWJ family emoji is seven codepoints and two cells. The host knows;
 * clients must not recompute. See the module docs.
 */
cells: number, text: string, };
