// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A monotonically increasing state number for one session.
 *
 * The client acknowledges the highest it has applied; the host uses that to
 * decide whether the next update can be a delta or has to be a keyframe. This
 * is the entire resync mechanism, and it is why the sequence counter already
 * exists in `zest-core`.
 */
export type Seq = bigint;
