// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionAddr } from "./SessionAddr";
import type { SessionContext } from "./SessionContext";

/**
 * A session as it appears in a listing.
 */
export type SessionInfo = { addr: SessionAddr, title: string, cwd: string, cols: number, rows: number, 
/**
 * True while a program has the alternate screen.
 *
 * The phone client switches from blocks view to grid view on exactly this
 * signal — `vim` and `htop` need a grid, everything else is better as a
 * list. Tracked host-side, so the decision is made from truth rather than
 * guessed from output.
 */
alt_screen: boolean, 
/**
 * Whether a client is currently attached.
 */
attached: boolean, 
/**
 * What the session is standing in — branch, venv, kube context — computed
 * by the daemon that owns it, so every client (and every agent) renders
 * the same chips without running anything in the user's shell.
 *
 * `#[serde(default)]` for the `HostOffer.os` reason: a required field an
 * older daemon omits fails the whole `Sessions` decode, which
 * `DaemonClient::recv` maps to a transport error, which costs the client
 * its connection. `None` is "the daemon did not say", never "no context".
 */
context?: SessionContext, 
/**
 * A command is running in this session right now.
 *
 * The tail block's word, so the ⌘K picker and the fleet cards can say it
 * for a session this window is not attached to — which they structurally
 * could not before: the listing carried nothing, and nothing pushed it on
 * a block transition anyway. False from a shell emitting no markers, like
 * every other blocks-derived fact.
 */
busy: boolean, };
