// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HostId } from "./HostId";
import type { SessionId } from "./SessionId";

/**
 * A session anywhere in the mesh.
 *
 * The unit every session-scoped message is addressed by. See the crate docs for
 * why the host half is not optional.
 */
export type SessionAddr = { host: HostId, session: SessionId, };
