// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionAddr } from "./SessionAddr";

/**
 * A session as it appears in a listing.
 */
export type SessionInfo = { addr: SessionAddr, title: string, cwd: string, cols: number, rows: number, 
/**
 * True while a program has the alternate screen.
 *
 * The phone client switches from blocks view to grid view on exactly this
 * signal — `vim` and `htop` need a grid, everything else is better as a
 * list. Tracked host-side, so the decision is made from truth rather than
 * guessed from output.
 */
alt_screen: boolean, 
/**
 * Whether a client is currently attached.
 */
attached: boolean, };
