// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContextFact } from "./ContextFact";
import type { GitContext } from "./GitContext";

/**
 * Where the session is standing, as its own daemon sees it.
 *
 * Everything here is *display*. A chip, a picker row, an agent's situational
 * awareness — never a gate: half of it comes from the filesystem as of a
 * debounce window ago, and the other half will come from shell-emitted
 * escapes anything that can print can forge (ADR-015's line, applied to
 * context instead of exit codes). Each fact says which half it is.
 */
export type SessionContext = { 
/**
 * The repository the cwd is inside, when it is inside one.
 */
git?: GitContext, 
/**
 * Everything else, as labeled strings: `venv`, `kube`, `node`, …
 *
 * The `HostOffer` philosophy — facts, deliberately, not a capability
 * matrix. A client meeting a key it does not know shows one chip fewer;
 * adding a fact is never a protocol change.
 */
facts: Array<ContextFact>, 
/**
 * Bumped by the producing daemon whenever this context changes, so a
 * client can skip rebuilding chrome for a listing push that moved for
 * some other reason. Monotonic per session, not wall time.
 *
 * `ts(type = "number")` for the #14 reason: `rmp-serde` writes the
 * narrowest integer that fits, so this reaches JavaScript as a plain
 * `number` for every count a daemon will ever reach.
 */
revision: number, };
