// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A detached Ed25519 signature.
 *
 * Hand-written `Debug`: a signature is 128 hex characters and appears in
 * tracing output at every connection, where the full value is noise that
 * pushes the useful fields off the line.
 */
export type Sig64 = string;
