// @generated by `cargo xtask export-web` -- do not edit.
//
// The built-in themes, serialized from `crates/zest-theme/src/builtin.rs`.
// These were hand-copied hex until this file existed; drift meant the native
// window and the browser disagreed about what `obsidian` looks like, with
// nothing to catch it. Run the command above after changing a builtin.

import type { Theme } from './tokens.ts';

export const obsidian: Theme = {
  id: 'obsidian',
  name: 'Obsidian',
  mode: 'dark',
  ui: {
    accent: '#6ea8ff',
    accentSoft: '#16203a',
    accentText: '#0b0f1a',
    bg: '#0b0f1a',
    black: '#0b0f1a',
    blue: '#6ea8ff',
    chrome: '#0b0f1a',
    cyan: '#5fc4e0',
    danger: '#e0606a',
    dim: '#8b93a7',
    faint: '#4a516a',
    fg: '#d7dcea',
    green: '#5fd17f',
    info: '#5fc4e0',
    line: '#2a3350',
    magenta: '#b07cff',
    panel: '#121829',
    red: '#e0606a',
    selSoft: '#161d33',
    shadow: '#000000',
    success: '#5fd17f',
    warn: '#e0b341',
    white: '#d7dcea',
    yellow: '#e0b341',
  },
};

export const nord: Theme = {
  id: 'nord',
  name: 'Nord',
  mode: 'dark',
  ui: {
    accent: '#81a1c1',
    accentSoft: '#3a4352',
    accentText: '#2e3440',
    bg: '#2e3440',
    black: '#3b4252',
    blue: '#81a1c1',
    chrome: '#323844',
    cyan: '#88c0d0',
    danger: '#bf616a',
    dim: '#989eaa',
    faint: '#69707c',
    fg: '#d8dee9',
    green: '#a3be8c',
    info: '#88c0d0',
    line: '#434955',
    magenta: '#b48ead',
    panel: '#363c48',
    red: '#bf616a',
    selSoft: '#404a5a',
    shadow: '#000000',
    success: '#a3be8c',
    warn: '#ebcb8b',
    white: '#e5e9f0',
    yellow: '#ebcb8b',
  },
};

export const gum: Theme = {
  id: 'gum',
  name: 'Gum',
  mode: 'dark',
  ui: {
    accent: '#7aa2ff',
    accentSoft: '#302b45',
    accentText: '#1f1b2a',
    bg: '#1f1b2a',
    black: '#2b2536',
    blue: '#7aa2ff',
    chrome: '#231f2e',
    cyan: '#5fd7e0',
    danger: '#ff5c8a',
    dim: '#9a95a5',
    faint: '#635f6f',
    fg: '#e6e1f0',
    green: '#5ce6a8',
    info: '#5fd7e0',
    line: '#373242',
    magenta: '#c792ea',
    panel: '#262232',
    red: '#ff5c8a',
    selSoft: '#383353',
    shadow: '#000000',
    success: '#5ce6a8',
    warn: '#ffc857',
    white: '#e6e1f0',
    yellow: '#ffc857',
  },
};

export const classic: Theme = {
  id: 'classic',
  name: 'Classic',
  mode: 'dark',
  ui: {
    accent: '#0000ee',
    accentSoft: '#050002',
    accentText: '#e5e5e5',
    bg: '#000000',
    black: '#000000',
    blue: '#0000ee',
    chrome: '#050505',
    cyan: '#00cdcd',
    danger: '#cd0000',
    dim: '#808080',
    faint: '#3a3a3a',
    fg: '#e5e5e5',
    green: '#00cd00',
    info: '#00cdcd',
    line: '#171717',
    magenta: '#cd00cd',
    panel: '#090909',
    red: '#cd0000',
    selSoft: '#0d0008',
    shadow: '#000000',
    success: '#00cd00',
    warn: '#cdcd00',
    white: '#e5e5e5',
    yellow: '#cdcd00',
  },
};

export const paper: Theme = {
  id: 'paper',
  name: 'Paper',
  mode: 'light',
  ui: {
    accent: '#1f6feb',
    accentSoft: '#e1e8cf',
    accentText: '#faf9f5',
    bg: '#faf9f5',
    black: '#2b2b2b',
    blue: '#1f6feb',
    chrome: '#f5f4f0',
    cyan: '#1b7c83',
    danger: '#c0392b',
    dim: '#646c6c',
    faint: '#9fa4a1',
    fg: '#24292f',
    green: '#27803a',
    info: '#1b7c83',
    line: '#d8d9d4',
    magenta: '#8250df',
    panel: '#f0efeb',
    red: '#c0392b',
    selSoft: '#d0e2c1',
    shadow: '#000000',
    success: '#27803a',
    warn: '#9a6b00',
    white: '#6e7781',
    yellow: '#9a6b00',
  },
};

/** All built-ins, in builtin.rs's `IDS` order -- the theme picker's order. */
export const builtinThemes: readonly Theme[] = [obsidian, nord, gum, classic, paper];

/** The defaults when nothing is configured (builtin.rs's `DEFAULT_DARK`/`_LIGHT`). */
export const DEFAULT_DARK = 'obsidian';
export const DEFAULT_LIGHT = 'paper';
